server:
  port: 7100

io:
  rsocket:
    broker:
      client:
        route-id: 00000000-0000-0000-0000-000000000001
        service-name: client-gateway
        tags:
          INSTANCE_NAME: client-gateway-1
        address:
          # Note: Not able to figure it out how to provide a route with common root level @MessageMapping annotation
          # and different method level @MessageMapping annotation e.g. route of format "simple.rr" where the simple
          # is root level route value of @MessageMapping annotation and rr is the route value of method level @MessageMapping annotation
          simple.rr:
            service_name: rsocket-server
          # Below rout configuration is working but above nested route is not
          # rr:
          #   service_name: rsocket-server
        brokers:
          - tcp://localhost:9010